### ISSUE TITLE
任务分配

### ISSUE THREAD

**Issue by jk2K** [samzhou/mobile-tech-media#1]
## meng
- [android weekly](https://androidweekly.net/)
- [android 中国](https://androidweekly.io)
- [ios weekly](https://iosdevweekly.com/)
- [ios 中国](https://github.com/SwiftOldDriver/iOS-Weekly)
- [蚂蚁金服科技](https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzI0Nzc3MTQyMw==&scene=124&#wechat_redirect)
- [美团技术团队](https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MjM5NjQ5MTI5OA==&scene=124&#wechat_redirect)
- [微信开放社区官方公告](https://developers.weixin.qq.com/community/develop/list/2)

## wei
- [reactjs weekly](http://reactjsnewsletter.com/)
- [Flutter Weekly](https://us17.campaign-archive.com/home/?u=c8d8d18b6e2c6316ddc1d48a0&id=47548a283b)
- [凹凸实验室](https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzIxMzExMjYwOQ==&scene=124&#wechat_redirect)
- [咸鱼技术](https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzU4MDUxOTI5NA==&scene=124&#wechat_redirect)
- [前端之巅](https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzUxMzcxMzE5Ng==&scene=124&#wechat_redirect)

**Comment by Hyduan** [comment]
👍

**Comment by Hyduan** [comment]
👍
